### ISSUE TITLE
Install ROS2 from source on PX2

### ISSUE THREAD

**Issue by dylan-gonzalez** [Monash-Connected-Autonomous-Vehicle/Twizy-Autoware-Shadow-Repo#3]
PX2 is currently on Ubuntu 16.04

Performing a kernel upgrade is an option for getting a working Ubuntu 22.04 installation - but this option is hard!

If we can install ROS2 from source on the PX2 then we might have a good solution! But you may enter dependency hell...

Should probably first try [Building ROS2 Eloquent from source](https://docs.ros.org/en/eloquent/Installation/Linux-Development-Setup.html) on Ubuntu 16.04 (PX2), and if that works then try other distros like foxy, humble, etc.

**Comment by ZileiChen** [comment]
12/10/23
Installing ROS2 from source. Using the link above


![Image](https://github.com/Monash-Connected-Autonomous-Vehicle/Twizy-Autoware-Shadow-Repo/assets/126771760/d8a654df-caff-4c62-b1cd-c1b105aee6e7)

Attempting to install in this directory

The following is given after the step "Install dependencies using rosdep"

![Image](https://github.com/Monash-Connected-Autonomous-Vehicle/Twizy-Autoware-Shadow-Repo/assets/126771760/ebc7db2b-0094-4a73-b063-c8c19eae595d)

Some warnings given are likely caused by having ros kinetic already installed in the PX2.
The errors given are because the the system dependency "python3-ifcfg" and "python-mock" are not installed/available on Ubuntu 16 Xenial
https://index.ros.org/d/python3-ifcfg/
https://index.ros.org/d/python-mock/
![Image](https://github.com/Monash-Connected-Autonomous-Vehicle/Twizy-Autoware-Shadow-Repo/assets/126771760/d560c36c-13d1-4ddf-bff1-62d09eb6a995)



After following the step

![Image](https://github.com/Monash-Connected-Autonomous-Vehicle/Twizy-Autoware-Shadow-Repo/assets/126771760/0a7be8d8-c403-4be5-9410-c1bbb07a628d)

This error is given


![Image](https://github.com/Monash-Connected-Autonomous-Vehicle/Twizy-Autoware-Shadow-Repo/assets/126771760/4dd495aa-0891-4d52-99c9-f635ff342f90)

**Comment by ZileiChen** [comment]
The full error is given below:


![Image](https://github.com/Monash-Connected-Autonomous-Vehicle/Twizy-Autoware-Shadow-Repo/assets/126771760/d899897e-2847-41f7-ab52-af6f7eb6379f)



![Image](https://github.com/Monash-Connected-Autonomous-Vehicle/Twizy-Autoware-Shadow-Repo/assets/126771760/d255db04-68b6-4eb1-ac9e-9abe9cf2037d)

These errors look like dependency errors.
Attempting to install/upgrade python3-setuptools does not work since the PX2 already has those installed.

Personally feel like most of the errors would be presented here as there are still 200+ packages not processed yet

**Comment by dylan-gonzalez** [comment]
Ok doesn't seem like it'll work then so no point spending more time at it

But just checking if you tried
`rosdep install --include-eol-distros` (since eloquent is EOL)

**Comment by ZileiChen** [comment]
No I haven't tried that

**Comment by dylan-gonzalez** [comment]
Maybe just try that because otherwise rosdep install will ignore all EOL distros meaning it won't work for Eloquent
And if that still doesn't work then feel free to close this issue
